---
title: "Informe - Análisis Descriptivo"
author: "Santiago Zuluaga Ayala"
date: "14/11/2020"
output: html_document
---

```{r include=FALSE}
library(dplyr)
library(ggplot2)
library(forcats)
library(lubridate)
library(scales)
library(zoo)
```

```{r include=FALSE}
df <- read.csv("Accidentalidad_Medellin.csv")
```

```{r include=FALSE}
# Vector con columnas a cambiar su tipo de dato
cols <- c("clase", "gravedad", "barrio", 
          "comuna", "diseno", "dia_nombre")

df[cols] <- lapply(df[cols], as.factor)

df$fecha <- as.Date(df$fecha, "%Y-%m-%d")
```

```{r include=FALSE}
# Seleccionamos columnas para el análisis descriptivo
df <- df %>% select(fecha, clase, gravedad, barrio, comuna, diseno)
```

## Accidentes por clase

```{r}
sum1 <- df %>%
        group_by(clase) %>%
          summarise(Total = n())
sum1 <- sum1[!sum1$clase %in% c("Choque y Atropello", "Incendio"),]
```

```{r}
ggplot(data = df %>% filter(!clase %in% c("Incendio", "Choque y Atropello")), 
       aes(x = reorder(clase, clase,
                     function(x)-length(x)))) +
      theme_minimal(base_size = 12.5) +
      theme(plot.title = element_text(hjust = 0.5),
      legend.title = element_text(size=9),
      panel.border = element_rect(colour = "black", fill=NA, size=1)) +
      labs(x = "Clase", y = "Número de accidentes") +
      ggtitle("Número de accidentes por clase") +
      geom_bar(color = "black", fill = "#EDBBA8", width=.6)
```

## Accidentes por diseño

```{r}
sum2 <- df %>%
        group_by(diseno) %>%
          summarise(Total = n())

sum2 <- sum2[order(sum2$Total, decreasing = T)[1:4],]
```


```{r}
ggplot(data = sum2 %>% mutate(diseno = fct_reorder(diseno, desc(Total))), 
       aes(x = diseno, y = Total)) +
      theme_minimal(base_size = 12.5) +
      theme(plot.title = element_text(hjust = 0.5),
      legend.title = element_text(size=9),
      panel.border = element_rect(colour = "black", fill=NA, size=1)) +
      labs(x = "Diseño de vía", y = "Número de accidentes") +
      ggtitle("Número de accidentes por diseño de vía") +
      geom_bar(stat = "identity", color = "black", fill = "#D7F4FA", width=.6)
```

## Mapa de calor

```{r}
df_dates <- read.csv("Accidentalidad_por_fechas_v2.csv")

df_dates <- df_dates %>%
          mutate(mes = as.factor(month(fecha)),
               ano_mes = as.factor(as.yearmon(fecha)),
               semana = week(fecha),
               semana_dia = as.factor(wday(fecha, label = TRUE)),
               ano = year(fecha),
               mes = month(fecha, label = TRUE)
               )
library(plyr)
df_dates <- ddply(df_dates,.(ano_mes), transform, mes_semana=1+semana-min(semana))  # compute week number of month
```

```{r out.width = '150%', out.height ='150%'}

ggplot(df_dates, aes(mes_semana, semana_dia, fill = total)) + 
  geom_tile(colour = "white") + 
  facet_grid(ano~mes) + 
  scale_fill_gradient(low="green", high="red") +
  labs(x="Semana del mes",
   y="",
   title = "Visualización del total de accidentes por fecha", 
   fill="Total de accidentes")
```
















